-- 혜택(청년정책) / 팁(블로그) / 저장(북마크) 콘텐츠 테이블

CREATE TABLE youth_policy (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id              VARCHAR(30) NOT NULL UNIQUE,
    title                    VARCHAR(500) NOT NULL,
    description              TEXT,
    support_content          TEXT,
    large_category           VARCHAR(200),
    medium_category          VARCHAR(200),
    supervising_org          VARCHAR(300),
    apply_url                TEXT,
    apply_period_text        VARCHAR(300),
    apply_deadline           DATE,
    apply_method             TEXT,
    submit_documents         TEXT,
    target_min_age           INTEGER,
    target_max_age           INTEGER,
    earn_condition           TEXT,
    additional_qualification TEXT,
    external_modified_at     VARCHAR(30),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_youth_policy_large_category ON youth_policy (large_category);

CREATE TABLE blog_tip (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(500) NOT NULL,
    description TEXT,
    category    VARCHAR(50),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE content_bookmark (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id BIGINT NOT NULL REFERENCES guest_user (id),
    content_type  VARCHAR(20) NOT NULL,
    content_id    BIGINT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (guest_user_id, content_type, content_id)
);

CREATE INDEX idx_content_bookmark_guest ON content_bookmark (guest_user_id, content_type);
