CREATE TABLE guest_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE refresh_token (
    id UUID PRIMARY KEY,
    guest_user_id BIGINT NOT NULL REFERENCES guest_user (id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);
