CREATE TABLE onboarding_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id         BIGINT NOT NULL UNIQUE REFERENCES guest_user (id),
    birth_date            DATE,
    monthly_salary_manwon INTEGER,
    monthly_saving_manwon INTEGER,
    net_worth_manwon      INTEGER,
    goal_period_months    INTEGER,
    status                VARCHAR(20) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE onboarding_goal (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id         BIGINT NOT NULL UNIQUE REFERENCES guest_user (id),
    plan                  VARCHAR(10) NOT NULL,
    period_months         INTEGER NOT NULL,
    monthly_saving_manwon INTEGER NOT NULL,
    uplift_permille       INTEGER NOT NULL,
    target_amount_manwon  INTEGER NOT NULL,
    config_version        VARCHAR(40) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL
);
