CREATE TABLE mission_survey (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id  BIGINT NOT NULL UNIQUE REFERENCES guest_user (id),
    schema_version VARCHAR(20) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    version        BIGINT NOT NULL
);

CREATE TABLE mission_survey_answer (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_survey_id BIGINT NOT NULL REFERENCES mission_survey (id) ON DELETE CASCADE,
    category_code     VARCHAR(20) NOT NULL,
    question_code     VARCHAR(50) NOT NULL,
    value_type        VARCHAR(10) NOT NULL,
    answer_code       VARCHAR(60) NOT NULL,
    numeric_value     INTEGER,
    unit_code         VARCHAR(30),
    CONSTRAINT uk_mission_survey_answer
        UNIQUE (mission_survey_id, category_code, question_code, answer_code),
    CONSTRAINT ck_mission_survey_answer_value_type
        CHECK (value_type IN ('OPTION', 'NUMBER')),
    CONSTRAINT ck_mission_survey_answer_shape
        CHECK (
            (value_type = 'OPTION' AND numeric_value IS NULL AND unit_code IS NULL)
            OR
            (
                value_type = 'NUMBER'
                AND numeric_value IS NOT NULL
                AND numeric_value >= 0
                AND unit_code IS NOT NULL
            )
        )
);
