CREATE TABLE mission_draft_template (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category              VARCHAR(20) NOT NULL,
    title                 VARCHAR(120) NOT NULL,
    description           VARCHAR(500) NOT NULL,
    action_code           VARCHAR(80) NOT NULL,
    metric_type           VARCHAR(20) NOT NULL,
    target_count          INTEGER NOT NULL,
    target_unit           VARCHAR(40) NOT NULL,
    estimated_savings_won INTEGER NOT NULL,
    sort_order            INTEGER NOT NULL,
    active                BOOLEAN NOT NULL,
    CONSTRAINT uk_mission_draft_template_order UNIQUE (category, sort_order),
    CONSTRAINT ck_mission_draft_template_category
        CHECK (category IN ('MEAL', 'TRANSPORT', 'HOBBY', 'LIVING')),
    CONSTRAINT ck_mission_draft_template_metric
        CHECK (metric_type IN ('COUNT', 'CHECK')),
    CONSTRAINT ck_mission_draft_template_values
        CHECK (target_count >= 0 AND estimated_savings_won >= 0)
);

CREATE TABLE mission_generation_job (
    id                       UUID PRIMARY KEY,
    guest_user_id            BIGINT NOT NULL REFERENCES guest_user (id),
    status                   VARCHAR(20) NOT NULL,
    active_generation_key    VARCHAR(20),
    failure_code             VARCHAR(80),
    generation_source        VARCHAR(30),
    expires_at               TIMESTAMP WITH TIME ZONE,
    confirmation_fingerprint VARCHAR(64),
    confirmed_at             TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    version                  BIGINT NOT NULL,
    CONSTRAINT uk_mission_generation_active UNIQUE (guest_user_id, active_generation_key),
    CONSTRAINT ck_mission_generation_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_mission_generation_active_key
        CHECK (
            (status IN ('PENDING', 'RUNNING') AND active_generation_key = 'ACTIVE')
            OR
            (status IN ('SUCCEEDED', 'FAILED') AND active_generation_key IS NULL)
        ),
    CONSTRAINT ck_mission_generation_source
        CHECK (
            (status = 'SUCCEEDED' AND generation_source IN ('MOCK', 'OPENAI', 'TEMPLATE_FALLBACK'))
            OR
            (status <> 'SUCCEEDED' AND generation_source IS NULL)
        )
);

CREATE TABLE mission_draft (
    id                    UUID PRIMARY KEY,
    job_id                UUID NOT NULL REFERENCES mission_generation_job (id) ON DELETE CASCADE,
    template_id           BIGINT NOT NULL REFERENCES mission_draft_template (id),
    category              VARCHAR(20) NOT NULL,
    title                 VARCHAR(120) NOT NULL,
    description           VARCHAR(500) NOT NULL,
    action_code           VARCHAR(80) NOT NULL,
    metric_type           VARCHAR(20) NOT NULL,
    target_count          INTEGER NOT NULL,
    target_unit           VARCHAR(40) NOT NULL,
    estimated_savings_won INTEGER NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_mission_draft_job_template UNIQUE (job_id, template_id),
    CONSTRAINT ck_mission_draft_category
        CHECK (category IN ('MEAL', 'TRANSPORT', 'HOBBY', 'LIVING')),
    CONSTRAINT ck_mission_draft_metric
        CHECK (metric_type IN ('COUNT', 'CHECK')),
    CONSTRAINT ck_mission_draft_values
        CHECK (target_count >= 0 AND estimated_savings_won >= 0)
);

CREATE TABLE mission (
    id                    UUID PRIMARY KEY,
    job_id                UUID NOT NULL REFERENCES mission_generation_job (id),
    draft_id              UUID NOT NULL UNIQUE REFERENCES mission_draft (id),
    guest_user_id         BIGINT NOT NULL REFERENCES guest_user (id),
    category              VARCHAR(20) NOT NULL,
    title                 VARCHAR(120) NOT NULL,
    description           VARCHAR(500) NOT NULL,
    action_code           VARCHAR(80) NOT NULL,
    metric_type           VARCHAR(20) NOT NULL,
    target_count          INTEGER NOT NULL,
    target_unit           VARCHAR(40) NOT NULL,
    estimated_savings_won INTEGER NOT NULL,
    status                VARCHAR(20) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_mission_category
        CHECK (category IN ('MEAL', 'TRANSPORT', 'HOBBY', 'LIVING')),
    CONSTRAINT ck_mission_metric
        CHECK (metric_type IN ('COUNT', 'CHECK')),
    CONSTRAINT ck_mission_status
        CHECK (status IN ('ACTIVE')),
    CONSTRAINT ck_mission_values
        CHECK (target_count >= 0 AND estimated_savings_won >= 0)
);

CREATE INDEX idx_mission_generation_job_guest_created
    ON mission_generation_job (guest_user_id, created_at);
CREATE INDEX idx_mission_draft_job ON mission_draft (job_id);
CREATE INDEX idx_mission_guest_status ON mission (guest_user_id, status);

INSERT INTO mission_draft_template
    (category, title, description, action_code, metric_type, target_count, target_unit, estimated_savings_won, sort_order, active)
VALUES
    ('MEAL', '배달 한 끼를 집밥으로 바꾸기', '이번 주 배달 식사 한 번을 집에서 준비한 식사로 바꿔보세요.', 'REPLACE_DELIVERY_WITH_HOME_MEAL', 'COUNT', 1, 'TIMES_PER_WEEK', 15000, 1, TRUE),
    ('MEAL', '유료 음료 한 번 줄이기', '카페나 편의점 음료 대신 직접 준비한 음료를 한 번 마셔보세요.', 'REDUCE_PAID_BEVERAGE', 'COUNT', 1, 'TIMES_PER_WEEK', 5000, 2, TRUE),
    ('MEAL', '냉장고 음식으로 식사하기', '이미 가지고 있는 식재료를 확인하고 한 끼를 해결해 보세요.', 'USE_REFRIGERATOR_FOOD', 'COUNT', 1, 'TIMES_PER_WEEK', 12000, 3, TRUE),
    ('MEAL', '추가 메뉴 없이 주문하기', '배달 주문 시 최소 주문 금액을 맞추기 위한 추가 메뉴를 피하세요.', 'AVOID_EXTRA_MENU', 'COUNT', 1, 'TIMES_PER_WEEK', 4000, 4, TRUE),
    ('TRANSPORT', '택시 한 번 대중교통으로 바꾸기', '가능한 이동 한 번을 택시 대신 대중교통으로 이동해 보세요.', 'REPLACE_TAXI_WITH_TRANSIT', 'COUNT', 1, 'TIMES_PER_WEEK', 12000, 1, TRUE),
    ('TRANSPORT', '가까운 거리 걸어가기', '가까운 거리 이동 한 번을 도보나 자전거로 바꿔보세요.', 'WALK_SHORT_DISTANCE', 'COUNT', 1, 'TIMES_PER_WEEK', 3000, 2, TRUE),
    ('TRANSPORT', '이동 전 저렴한 경로 확인하기', '출발 전에 안전하고 비용이 낮은 이동 경로를 한 번 확인하세요.', 'CHECK_AFFORDABLE_ROUTE', 'CHECK', 1, 'TIMES_PER_WEEK', 2000, 3, TRUE),
    ('TRANSPORT', '외출 일정 묶어서 처리하기', '여러 외출 일정을 한 번의 이동으로 처리할 수 있는지 점검하세요.', 'BUNDLE_TRIPS', 'CHECK', 1, 'TIMES_PER_WEEK', 4000, 4, TRUE),
    ('HOBBY', '취미 구매 전 24시간 기다리기', '사고 싶은 취미 상품이 생기면 결제 전에 하루 동안 기다려 보세요.', 'WAIT_BEFORE_HOBBY_PURCHASE', 'COUNT', 1, 'TIMES_PER_WEEK', 10000, 1, TRUE),
    ('HOBBY', '가지고 있는 취미 용품 사용하기', '새로 구매하지 않고 이미 가진 용품이나 콘텐츠를 한 번 사용하세요.', 'USE_OWNED_HOBBY_ITEM', 'COUNT', 1, 'TIMES_PER_WEEK', 8000, 2, TRUE),
    ('HOBBY', '취미 구독 점검하기', '현재 결제 중인 취미 구독의 실제 이용 여부를 확인하세요.', 'REVIEW_HOBBY_SUBSCRIPTION', 'CHECK', 1, 'TIMES_PER_WEEK', 5000, 3, TRUE),
    ('HOBBY', '대여나 중고 먼저 확인하기', '취미 물품을 구매하기 전에 대여나 중고 대안을 한 번 확인하세요.', 'CHECK_RENTAL_OR_USED', 'CHECK', 1, 'TIMES_PER_WEEK', 10000, 4, TRUE),
    ('LIVING', '온라인 쇼핑 전 24시간 기다리기', '온라인 장바구니 상품을 바로 결제하지 말고 하루 동안 기다려 보세요.', 'WAIT_BEFORE_ONLINE_PURCHASE', 'COUNT', 1, 'TIMES_PER_WEEK', 12000, 1, TRUE),
    ('LIVING', '구매 전 집에 있는 재고 확인하기', '생활용품을 사기 전에 집에 남은 재고를 한 번 확인하세요.', 'CHECK_HOME_INVENTORY', 'CHECK', 1, 'TIMES_PER_WEEK', 6000, 2, TRUE),
    ('LIVING', '생활 구독 점검하기', '정기 결제 중인 생활 구독의 이용 여부를 확인하세요.', 'REVIEW_LIVING_SUBSCRIPTION', 'CHECK', 1, 'TIMES_PER_WEEK', 5000, 3, TRUE),
    ('LIVING', '쇼핑 목록에 있는 것만 구매하기', '필요한 물건을 목록으로 만들고 목록 밖의 구매를 한 번 피하세요.', 'FOLLOW_SHOPPING_LIST', 'COUNT', 1, 'TIMES_PER_WEEK', 8000, 4, TRUE);
