CREATE TABLE goal (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id          BIGINT NOT NULL UNIQUE REFERENCES guest_user (id),
    target_amount_manwon   INTEGER NOT NULL,
    period_months          INTEGER NOT NULL,
    monthly_target_manwon  INTEGER NOT NULL,
    base_amount_manwon     INTEGER NOT NULL,
    started_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE saving_record (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id BIGINT NOT NULL REFERENCES guest_user (id),
    amount_manwon INTEGER NOT NULL,
    recorded_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_saving_record_guest_recorded ON saving_record (guest_user_id, recorded_at);
