CREATE TABLE goal (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id          BIGINT NOT NULL UNIQUE REFERENCES guest_user (id),
    target_amount_manwon   INTEGER NOT NULL,
    period_months          INTEGER NOT NULL,
    monthly_target_manwon  INTEGER NOT NULL,
    base_amount_manwon     INTEGER NOT NULL,
    started_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    version                BIGINT NOT NULL
);

CREATE TABLE monthly_saving (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id       BIGINT NOT NULL REFERENCES guest_user (id),
    year_month          VARCHAR(7) NOT NULL,
    saved_amount_manwon INTEGER NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (guest_user_id, year_month)
);
