-- 저축액 입력을 누적(append)에서 이번 달 값 덮어쓰기(월별 1행)로 변경한다.
-- saving_record(append 이벤트)는 아직 사용 데이터가 없어 제거하고, 월별 저축액 테이블로 교체한다.
DROP TABLE saving_record;

CREATE TABLE monthly_saving (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_user_id       BIGINT NOT NULL REFERENCES guest_user (id),
    year_month          VARCHAR(7) NOT NULL,
    saved_amount_manwon INTEGER NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (guest_user_id, year_month)
);
