spring:
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
